### PR TITLE
SHS-NG M9: Stage page speed up.

### PR DESCRIPTION
**Pull request by vanzin**
There are two main changes to speed up rendering of the tasks list
when rendering the stage page.

The first one makes the code only load the tasks being shown in the
current page of the tasks table, and information related to only
those tasks. One side-effect of this change is that the graph that
shows task-related events now only shows events for the tasks in
the current page, instead of the previously hardcoded limit of "events
for the first 1000 tasks". That ends up helping with readability,
though.

To make sorting efficient when using a disk store, the task wrapper
was extended to include many new indices, one for each of the sortable
columns in the UI, and metrics for which quantiles are calculated.

The second changes the way metric quantiles are calculated for stages.
Instead of using the "Distribution" class to process data for all task
metrics, which requires scanning all tasks of a stage, the code now
uses the KVStore "skip()" functionality to only read tasks that contain
interesting information for the quantiles that are desired.

This is still not cheap; because there are many metrics that the UI
and API track, the code needs to scan the index for each metric to
gather the information. Savings come mainly from skipping deserialization
when using the disk store, but the in-memory code also seems to be
faster than before (most probably because of other changes in this
patch).

With the above changes, a lot of code in the UI layer could be simplified.

### CODE REVIEW

**Comment by libratiger** [comment]
is this branch stable enough now?

**Comment by libratiger** [comment]
I just run the UnitTesst, and found some test failed:

>stage task summary w shuffle write
>stage task summary w shuffle read
>stage task list w/ sortBy
>stage task list w/ sortBy short names
>job progress bars / cells reflect skipped stages

**Comment by vanzin** [comment]
@djvulee there's a couple of things I need to fix in this last patch... if you just reset the branch to the previous commit things should be more stable.

**Comment by vanzin** [comment]
Unit tests should be fixed in this patch too, now.

**Comment by libratiger** [comment]
Ok, Thanks!   I found the current branch can not deal with the failed Stage well enough, it will produce the following error:


> java.lang.IndexOutOfBoundsException: Page 1 is out of range. Please select a page number between 1 and 0.
	at org.apache.spark.ui.PagedDataSource.pageData(PagedTable.scala:56)
	at org.apache.spark.ui.PagedTable$class.table(PagedTable.scala:108)
	at org.apache.spark.ui.jobs.TaskPagedTable.table(StagePage.scala:702)
	at org.apache.spark.ui.jobs.StagePage.liftedTree1$1(StagePage.scala:295)
	at org.apache.spark.ui.jobs.StagePage.render(StagePage.scala:284)
	at org.apache.spark.ui.WebUI$$anonfun$2.apply(WebUI.scala:82)
	at org.apache.spark.ui.WebUI$$anonfun$2.apply(WebUI.scala:82)
	at org.apache.spark.ui.JettyUtils$$anon$3.doGet(JettyUtils.scala:88)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.spark_project.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.spark_project.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
	at org.apache.spark.deploy.history.ApplicationCacheCheckFilter.doFilter(ApplicationCache.scala:437)
	at org.spark_project.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at org.spark_project.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.spark_project.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.spark_project.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.spark_project.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.spark_project.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.spark_project.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.spark_project.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.spark_project.jetty.server.Server.handle(Server.java:524)
	at org.spark_project.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.spark_project.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.spark_project.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.spark_project.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.spark_project.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.spark_project.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.spark_project.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.spark_project.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.spark_project.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.spark_project.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)

**Comment by libratiger** [comment]
Another issue is that the SQL tab page will lead to nullPointerException(M8 branch)

**Comment by vanzin** [comment]
@djvulee do you have some code that can reproduce the failed stage you're having trouble with? I can't see any issues in my local build. The SQL tab and individual executions also render fine for me.

**Comment by libratiger** [comment]
@vanzin I do not have the code, I just click some log history, and find this issue. 

I will look through the code in the following days.

**Comment by vanzin** [comment]
If there's any code or even event logs you can share that would help a lot. The logs and code I've been testing with all seem pretty happy.

**Comment by libratiger** [comment]
Ok, I will share the log if possible.

**Comment by zhouyejoe** [comment]
Hi, Marcelo. Thanks for your work on improving SHS. I have compiled locally and started instance pointing to our own spark job history data and it is now working fine. But I found two issues that will still slow down the SHS. 
1. The home page showing up time is trying to gathering all the applications in the application list in FsHistoryProvider. If we have more than 40K apps in HDFS folder, the rendering of the home page will be pretty slow as it needs to build the result for 40K apps which is unnecessary.
2. The rest API call to get stages/jobs/env information can get the result from DB which is pretty fast. But when user tries to click on the appID on the history home page, HistoryServer will still try to  get the data from ApplicationCache, if not in cache, FsHistoryProvider has to replay the whole log file. But sometimes the logs will be really large, and it will cost long time to replay the whole log. Is it possible that we can construct the info from what we already have in DB? 
I would like to contribute to add these two parts of the codes if it is doable and also not in your recent plan, as I didn't find it in your original design doc as mentioned in the upstream ticket.
Thanks.

**Comment by vanzin** [comment]
Hi @zhouyejoe ,

> If we have more than 40K apps in HDFS folder, the rendering of the home page will be pretty slow

Yes, that is true. That is independent of where the listing is stored though. Right now pagination is done client-side, and to fix this it should be done server-side. I don't think there's a bug tracking this feature, so feel free to file one.

> try to get the data from ApplicationCache, if not in cache, FsHistoryProvider has to replay the whole log file

Yes. The data in the listing DB does not contain all of the data to build the application's UI, so if the UI has never been loaded, the whole event log needs to be parsed.

I filed SPARK-20656 to make this better in the future; basically, with data stored on disk, we could speculatively parse logs (e.g. keep parsing logs of in-progress applications as they're written to, so that when the application finishes the SHS is pretty much up to date). But I'm only planning to look at that after the initial work is in.

**Pull request closed without merging**
